---
# tasks file for mapr_external_packages

- name: install EPEL 6
  tags:
    - metrics
    - external
  yum: name=http://dl.fedoraproject.org/pub/epel/6/x86_64/epel-release-6-8.noarch.rpm state=installed
  environment: proxy_env
  when: ansible_distribution not in ('Amazon', 'Ubuntu')

- name: enable EPEL 6
  tags:
    - metrics
    - external
  copy: src=epel.repo dest=/etc/yum.repos.d/epel.repo owner=root group=root mode=0644
  when: ansible_distribution in ('Amazon')

- name: install nice to have packages
  yum: name={{item}} state=present
  with_items:
    - jq
    - wget
